version: '3.8'

services:
  backend:
    build: .
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - storage_db
  storage_db:
    image: postgres:15-alpine
    container_name: storage_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
